### PR TITLE
Moved from SimplePool to ThreadPoolExecutor.

### LINKED ISSUE #78: Use ThreadPoolExecutor
We can use this instead of SimplePool. This will result in removal of one dependancy.
https://docs.python.org/3.3/library/concurrent.futures.html#threadpoolexecutor

### PR DESCRIPTION
**Pull request by ssundarraj**
Fixes #78

### CODE REVIEW

**Comment by ssundarraj** [comment]
Travis reports that concurrent.futures doesn't exist even though futures is included in the requirements.txt. I think the issue with this is that you've asked it to `pip install ImageScraper` then run the tests from the repo. Instead, it should run `python setup.py install` and then run the tests.

**Comment by sananth12** [comment]
You're correct. I'll fix the travis.yml and merge

**Comment by ssundarraj** [comment]
It's still failing for Python3 for some reason.

**Comment by ssundarraj** [comment]
@sananth12 
There doesn't seem to be a large performance difference when testing on imgur.com/topic/funny. But it's more of a stability issue. futures is a more mature module.

**Comment by sananth12** [comment]
@ssundarraj  I think there is a problem in the installation of futures in py3

**Pull request merged**
